# Generated by Django 4.2.5 on 2023-09-22 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("siteuser", "0003_alter_customerloan_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="loanTransaction",
            fields=[
                (
                    "transaction",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment", models.PositiveIntegerField(default=0)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_customer",
                        to="siteuser.siteuser",
                    ),
                ),
            ],
        ),
    ]
