# Generated by Django 4.2.5 on 2023-09-24 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteuser", "0004_loantransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanrequest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="loanrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="loantransaction",
            name="customer",
        ),
        migrations.DeleteModel(
            name="CustomerLoan",
        ),
        migrations.DeleteModel(
            name="loanCategory",
        ),
        migrations.DeleteModel(
            name="loanRequest",
        ),
        migrations.DeleteModel(
            name="loanTransaction",
        ),
    ]
