# Generated by Django 4.2.5 on 2023-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteuser", "0005_remove_loanrequest_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="admin_wallet",
            field=models.BooleanField(default=False),
        ),
    ]
